// 云无云 API 全面探测 - 基于路径模式猜测
import { query } from './server/yunwuyun.js';
import fs from 'fs';

const results = [];

// 所有可能的 API 前缀组合
const paths = [
  // 订单相关 - 各种可能的路径
  '/api/fms/ebi/fbx/page',
  '/api/fms/ebi/fbx/list',
  '/api/fms/ebi/fbx/query',
  '/api/fms/ebi/fbx/search',
  '/api/fms/ebi/fbx/queryByPage',
  '/api/fms/ebi/fbx/queryList',
  '/api/fms/ebi/order/page',
  '/api/fms/ebi/order/list',
  '/api/fms/ebi/order/query',
  '/api/fms/ebi/order/queryByPage',
  '/api/fms/ebi/order/queryList',
  '/api/fms/ebi/bizOrder/page',
  '/api/fms/ebi/bizOrder/list',
  '/api/fms/ebi/bizOrder/query',
  '/api/fms/ebi/bizOrder/queryByPage',
  '/api/fms/ebi/bizOrder/queryList',
  '/api/fms/bizOrder/queryOrder',
  '/api/fms/bizOrder/queryOrderList',
  '/api/fms/bizOrder/queryOrderByPage',
  '/api/fms/bizOrder/getOrderList',
  '/api/fms/bizOrder/getOrderByPage',
  '/api/fms/bizOrder/findOrder',
  '/api/fms/bizOrder/findOrderList',
  '/api/fms/bizOrder/findOrderByPage',
  '/api/fms/order/query',
  '/api/fms/order/list',
  '/api/fms/order/page',
  '/api/fms/order/queryByPage',
  '/api/fms/order/queryList',
  '/api/fms/order/search',
  '/api/fms/order/findOrderList',
  '/api/fms/order/getOrderList',
  '/api/fms/order/getOrderByPage',
  '/api/fms/order/getList',
  '/api/order/query',
  '/api/order/list',
  '/api/order/page',
  '/api/order/queryByPage',
  '/api/order/queryList',
  '/api/order/search',
  '/api/fms/biz/order/query',
  '/api/fms/biz/order/list',
  '/api/fms/biz/order/page',
  '/api/fms/biz/order/queryByPage',
  '/api/fms/biz/order/queryList',
  '/api/fms/biz/order/search',
  '/api/fms/bizOrderInfo/query',
  '/api/fms/bizOrderInfo/list',
  '/api/fms/bizOrderInfo/page',
  '/api/fms/bizOrderInfo/queryByPage',
  '/api/fms/bizOrderInfo/queryList',
  '/api/fms/ebizOrder/query',
  '/api/fms/ebizOrder/list',
  '/api/fms/ebizOrder/page',
  '/api/fms/ebizOrder/queryByPage',
  '/api/fms/ebizOrder/queryList',
  '/api/fms/ebi/orderInfo/query',
  '/api/fms/ebi/orderInfo/list',
  '/api/fms/ebi/orderInfo/page',
  '/api/fms/ebi/orderInfo/queryByPage',
  '/api/fms/ebi/orderInfo/queryList',
  '/api/fms/ebi/orderInfo/search',
  '/api/fms/ebi/fbx/orderInfo/query',
  '/api/fms/ebi/fbx/orderInfo/list',
  '/api/fms/ebi/fbx/orderInfo/page',
  '/api/fms/ebi/fbx/orderInfo/queryByPage',
  '/api/fms/ebi/fbx/orderInfo/queryList',
  '/api/fms/ebi/fbx/orderInfo/search',
  '/api/fms/ebi/fbx/order/query',
  '/api/fms/ebi/fbx/order/list',
  '/api/fms/ebi/fbx/order/page',
  '/api/fms/ebi/fbx/order/queryByPage',
  '/api/fms/ebi/fbx/order/queryList',
  '/api/fms/ebi/fbx/order/search',
  '/api/fms/ebi/fbxData/query',
  '/api/fms/ebi/fbxData/list',
  '/api/fms/ebi/fbxData/page',
  '/api/fms/ebi/fbxData/queryByPage',
  '/api/fms/ebi/fbxData/queryList',
  '/api/fms/ebi/fbxData/search',
  '/api/fms/ebi/data/query',
  '/api/fms/ebi/data/list',
  '/api/fms/ebi/data/page',
  '/api/fms/ebi/data/queryByPage',
  '/api/fms/ebi/data/queryList',
  '/api/fms/ebi/data/search',
  '/api/fms/ebi/biz/query',
  '/api/fms/ebi/biz/list',
  '/api/fms/ebi/biz/page',
  '/api/fms/ebi/biz/queryByPage',
  '/api/fms/ebi/biz/queryList',
  '/api/fms/ebi/biz/search',
  '/api/fms/ebi/query',
  '/api/fms/ebi/list',
  '/api/fms/ebi/page',
  '/api/fms/ebi/queryByPage',
  '/api/fms/ebi/queryList',
  '/api/fms/ebi/search',
  '/api/fms/fbx/query',
  '/api/fms/fbx/list',
  '/api/fms/fbx/page',
  '/api/fms/fbx/queryByPage',
  '/api/fms/fbx/queryList',
  '/api/fms/fbx/search',
  '/api/fms/ebiOrder/query',
  '/api/fms/ebiOrder/list',
  '/api/fms/ebiOrder/page',
  '/api/fms/ebiOrder/queryByPage',
  '/api/fms/ebiOrder/queryList',
  '/api/fms/ebiOrder/search',

  // 客户相关
  '/api/fms/ebi/customer/query',
  '/api/fms/ebi/customer/list',
  '/api/fms/ebi/customer/page',
  '/api/fms/ebi/customer/queryByPage',
  '/api/fms/ebi/customer/queryList',
  '/api/fms/ebi/customer/search',
  '/api/fms/customerInfo/query',
  '/api/fms/customerInfo/list',
  '/api/fms/customerInfo/page',
  '/api/fms/customerInfo/queryByPage',
  '/api/fms/customerInfo/queryList',
  '/api/fms/customerInfo/search',
  '/api/fms/cust/query',
  '/api/fms/cust/list',
  '/api/fms/cust/page',
  '/api/fms/cust/queryByPage',
  '/api/fms/cust/queryList',
  '/api/fms/cust/search',
  '/api/fms/crm/customer/query',
  '/api/fms/crm/customer/list',
  '/api/fms/crm/customer/page',
  '/api/fms/crm/customer/queryByPage',
  '/api/fms/crm/customer/queryList',
  '/api/fms/crm/customer/search',
  '/api/fms/client/query',
  '/api/fms/client/list',
  '/api/fms/client/page',
  '/api/fms/client/queryByPage',
  '/api/fms/client/queryList',
  '/api/fms/client/search',
  '/api/fms/partner/query',
  '/api/fms/partner/list',
  '/api/fms/partner/page',
  '/api/fms/partner/queryByPage',
  '/api/fms/partner/queryList',
  '/api/fms/partner/search',
  '/api/fms/supplier/query',
  '/api/fms/supplier/list',
  '/api/fms/supplier/page',
  '/api/fms/supplier/queryByPage',
  '/api/fms/supplier/queryList',
  '/api/fms/supplier/search',
  '/api/fms/ebi/supplier/query',
  '/api/fms/ebi/supplier/list',
  '/api/fms/ebi/supplier/page',
  '/api/fms/ebi/supplier/queryByPage',
  '/api/fms/ebi/supplier/queryList',
  '/api/fms/ebi/supplier/search',
  '/api/fms/ebi/cust/query',
  '/api/fms/ebi/cust/list',
  '/api/fms/ebi/cust/page',
  '/api/fms/ebi/cust/queryByPage',
  '/api/fms/ebi/cust/queryList',
  '/api/fms/ebi/cust/search',
  '/api/fms/ebi/company/query',
  '/api/fms/ebi/company/list',
  '/api/fms/ebi/company/page',
  '/api/fms/ebi/company/queryByPage',
  '/api/fms/ebi/company/queryList',
  '/api/fms/ebi/company/search',
  '/api/fms/ebi/client/query',
  '/api/fms/ebi/client/list',
  '/api/fms/ebi/client/page',
  '/api/fms/ebi/client/queryByPage',
  '/api/fms/ebi/client/queryList',
  '/api/fms/ebi/client/search',
  '/api/fms/ebi/partner/query',
  '/api/fms/ebi/partner/list',
  '/api/fms/ebi/partner/page',
  '/api/fms/ebi/partner/queryByPage',
  '/api/fms/ebi/partner/queryList',
  '/api/fms/ebi/partner/search',
  '/api/fms/ebi/fbxCustomer/query',
  '/api/fms/ebi/fbxCustomer/list',
  '/api/fms/ebi/fbxCustomer/page',
  '/api/fms/ebi/fbxCustomer/queryByPage',
  '/api/fms/ebi/fbxCustomer/queryList',
  '/api/fms/ebi/fbxCustomer/search',
  '/api/fms/ebi/fbxClient/query',
  '/api/fms/ebi/fbxClient/list',
  '/api/fms/ebi/fbxClient/page',
  '/api/fms/ebi/fbxClient/queryByPage',
  '/api/fms/ebi/fbxClient/queryList',
  '/api/fms/ebi/fbxClient/search',
  '/api/fms/ebi/fbxPartner/query',
  '/api/fms/ebi/fbxPartner/list',
  '/api/fms/ebi/fbxPartner/page',
  '/api/fms/ebi/fbxPartner/queryByPage',
  '/api/fms/ebi/fbxPartner/queryList',
  '/api/fms/ebi/fbxPartner/search',

  // 利润相关
  '/api/report/unirepproject/cntProfitTotal',
  '/api/report/unirepproject/cntProfitDetail',
  '/api/report/unirepproject/cntProfitGroup',
  '/api/report/unirepproject/cntProfitByCustomer',
  '/api/report/unirepproject/cntProfitByMonth',
  '/api/report/unirepproject/cntProfitByDate',
  '/api/report/unirepproject/cntProfitReport',
  '/api/report/unirepproject/profitTotal',
  '/api/report/unirepproject/profitDetail',
  '/api/report/unirepproject/profitGroup',
  '/api/report/unirepproject/profitReport',
  '/api/report/unirepproject/profitSummary',
  '/api/report/unirepproject/profitList',
  '/api/report/unirepproject/profitByCustomer',
  '/api/report/unirepproject/profitByMonth',
  '/api/report/unirepproject/profitByDate',
  '/api/report/unirepproject/financeProfit',
  '/api/report/unirepproject/financeProfitTotal',
  '/api/report/unirepproject/financeProfitDetail',
  '/api/report/unirepproject/financeProfitGroup',
  '/api/report/unirepproject/financeProfitByCustomer',
  '/api/report/unirepproject/financeProfitByMonth',
  '/api/report/unirepproject/financeProfitByDate',
  '/api/report/unirepproject/financeProfitReport',
  '/api/report/unirepproject/financeProfitSummary',
  '/api/report/unirepproject/financeProfitList',
  '/api/report/unirepproject/incomeTotal',
  '/api/report/unirepproject/incomeDetail',
  '/api/report/unirepproject/incomeReport',
  '/api/report/unirepproject/incomeSummary',
  '/api/report/unirepproject/incomeList',
  '/api/report/unirepproject/incomeGroup',
  '/api/report/unirepproject/incomeByCustomer',
  '/api/report/unirepproject/incomeByMonth',
  '/api/report/unirepproject/incomeByDate',
  '/api/report/unirepproject/costTotal',
  '/api/report/unirepproject/costDetail',
  '/api/report/unirepproject/costReport',
  '/api/report/unirepproject/costSummary',
  '/api/report/unirepproject/costList',
  '/api/report/unirepproject/costGroup',
  '/api/report/unirepproject/costByCustomer',
  '/api/report/unirepproject/costByMonth',
  '/api/report/unirepproject/costByDate',
];

let count = 0;
for (const path of paths) {
  try {
    const data = await query(path, { method: 'POST', body: { page: 1, size: 2 } });
    const success = data && (data.success === true || data.code === 200);
    if (success) {
      count++;
      const total = data?.result?.total || data?.result?.length || '?';
      const hasRecords = !!data?.result?.records || !!data?.result?.length;
      results.push({ path, method: 'POST', success: true, total, hasRecords, data });
      console.log(`✅ [${count}] POST ${path} -> 成功, total=${total}, hasRecords=${hasRecords}`);
    }
  } catch (err) {
    // skip
  }
}

fs.writeFileSync('yunwuyun-api-discovery.json', JSON.stringify(results, null, 2));
console.log(`\n=== 共发现 ${count} 个可用 POST 接口 ===`);

// 打印第一个成功接口的数据结构
if (results.length > 0) {
  console.log('\n=== 第一个接口返回数据结构示例 ===');
  console.log(JSON.stringify(results[0].data, null, 2).slice(0, 2000));
}